using AutoMapper;
using HMS.Application.Dto;
using HMS.Application.Dto.Doctor;
using HMS.Application.DTO;
using HMS.Application.DTO.Allergy;
using HMS.Application.DTO.Department;
using HMS.Application.DTO.Doctor;
using HMS.Application.DTO.Insurance;
using HMS.Application.DTO.MedicalHistory;
using HMS.Application.DTO.Patient;
using HMS.Application.DTOs.PatientVisitDtos;
using HMS.Domain.Entities;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace HMS.Application.Mappings
{
    public class MappingProfile : Profile
    {
        public MappingProfile()
        {
            // Create Mappings between Entity ↔ DTOs
            CreateMap<Patient, CreatePatientDto>().ReverseMap();
            CreateMap<Patient, UpdatePatientDto>().ReverseMap();
            CreateMap<Patient, PatientDto>().ReverseMap();
            CreateMap<CreateMedicalHistoryDto, MedicalHistory>().ReverseMap();
            CreateMap<MedicalHistory, GetPatientMedicalHistoryDto>().ReverseMap();
            CreateMap<EditMedicalHistoryDto, MedicalHistory>().ReverseMap();
            CreateMap<AddAllergyDto, Allergy>().ReverseMap();
            CreateMap<Allergy, ViewAllergyDto>().ReverseMap();
            CreateMap<Allergy, EditAllergyDto>().ReverseMap();
            CreateMap<AddAllergyDto, Allergy>().ReverseMap();
            CreateMap<AddInsuranceDto, Insurance>().ReverseMap();
            CreateMap<Insurance, ViewInsuranceDto>().ReverseMap();
            CreateMap<Insurance, EditInsuranceDto>().ReverseMap();
            CreateMap<AddPatientVisitDto, PatientVisit>().ReverseMap();
            CreateMap<PatientVisit, PatientVisitDto>()
                .ForMember(dest => dest.PatientName, opt => opt.MapFrom(src => src.Patient.FullName));
            CreateMap<PatientVisitUpdateDto, PatientVisit>()
                .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));
            // AddDoctorDto -> Doctor
            CreateMap<AddDoctorDto, Doctor>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())          // Id is generated by DB
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => DateTime.UtcNow))
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore());  // W
            CreateMap<Doctor, GetDoctorsDto>()
            .ForMember(dest => dest.FullName,
                       opt => opt.MapFrom(src => $"{src.FirstName} {src.LastName}"));
            CreateMap<EditDoctorDto, Doctor>()
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => DateTime.UtcNow));
            CreateMap<AddDepartmentsDto, Department>().ReverseMap();
            CreateMap<Department, DepartmentDto>().ReverseMap();
            CreateMap<Department, EditDepartmentDto>().ReverseMap();
        }
    }
}
